app/main/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

main = Blueprint("main", __name__)

from . import views

app/main/views.py
# -*- coding:utf-8 -*-

from flask import render_template, redirect, url_for, flash, session, request, make_response, g, jsonify
from app.main.forms import DemoForm, DemandForm, CodeForm, CommentForm, CommentForm1, ResolveForm, GradeForm, \
    ImproveForm, PortraitForm
from app.models import User, Enterprise, Tag, Demo, Demand, Demo_Review, Demo_Discuss, Demand_Review, Demand_Discuss, \
    Resolve, Improve
from . import main
from app import db, app
from app.decorators import user_login_reg, enterprise_login_reg, person_login_reg
import uuid, os, datetime, pickle, random
from app.ext.ext import remove_tag, change_list_to_dic, runningcode
from app.ext.interest_recommand import interest_recommmand_demand, interest_recommmand_demo
from app.ext.generator import generate_graph


def scatter3d():
    from pyecharts import Scatter3D

    data = [[random.randint(0, 100), random.randint(0, 100), random.randint(0, 100)] for _ in range(80)]
    range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
                   '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
    scatter3D = Scatter3D("3D scattering plot demo", width=1200, height=600)
    scatter3D.add("", data, is_visualmap=True, visual_range_color=range_color)
    return scatter3D.render_embed()


# import jieba.analyse


# jieba.analyse.set_stop_words(app.static_folder+'/keyword/'+'stopword.txt')
# jieba.load_userdict(app.static_folder+'/keyword/'+'ai.txt')


def change_filename(filename):
    fname, fext = os.path.splitext(filename)
    filename_prefix = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    return '%s%s%s' % (filename_prefix, str(uuid.uuid4().hex), fext)


# 测试echarts用
@main.route('/echartstest/')
def echartstest():
    return render_template('base/echarts.html', myechart=scatter3d())


# 测试charts用
@main.route('/test/')
def test():
    return render_template('base/test.html')


# 主页
@main.route('/')
def index():
    if hasattr(g, 'user'):
        re_demos = interest_recommmand_demo(g.user)
        re_demands = interest_recommmand_demand(g.user)
        re_users = User.query.all()
        if len(re_demos) < 9:
            l = len(re_demos)
            for demo in Demo.query.order_by(Demo.addtime.asc()).all():
                if l == 8:
                    break
                if demo not in re_demos:
                    re_demos.append(demo)
                    l = l + 1
        if len(re_demands) < 9:
            for demand in Demand.query.order_by(Demand.addtime.asc()).all():
                l = len(re_demands)
                if l == 8:
                    break
                if demand not in re_demands:
                    re_demands.append(demand)
                    l = l + 1
    else:
        re_demos = Demo.query.all()
        re_demands = Demand.query.all()
        re_users = User.query.all()

    new_demos = Demo.query.order_by(
        Demo.addtime.desc()
    ).all()
    new_demands = Demand.query.order_by(
        Demand.addtime.desc()
    ).all()
    new_users = User.query.order_by(
        User.addtime.desc()
    ).all()

    hot_demos = Demo.query.order_by(
        Demo.star.desc()
    ).all()
    hot_demands = Demand.query.order_by(
        Demand.star.desc()
    ).all()
    hot_users = User.query.order_by(
        User.fans.desc()
    ).all()

    return render_template('main/index.html', re_demos=re_demos[0:8], re_demands=re_demands[0:8],
                           re_users=re_users[0:8],
                           new_demos=new_demos[0:8], new_demands=new_demands[0:8], new_users=new_users[0:8],
                           hot_demos=hot_demos[0:8], hot_demands=hot_demands[0:8], hot_users=hot_users[0:8])


# demo
@main.route('/resolve/release/<int:demand_id>/', methods=['GET', 'POST'])
@user_login_reg
def resolve_release(demand_id=None):
    demand = Demand.query.get_or_404(int(demand_id))
    form = ResolveForm()
    if form.validate_on_submit():
        data = form.data
        url = ""
        if form.url.data:
            file_url = form.url.data.filename
            if not os.path.exists(app.config["UP_RESOLVE"] + g.user.uuid + '/'):  # 如果不存在，则创建文件
                os.makedirs(app.config["UP_RESOLVE"] + g.user.uuid + '/')
                # os.chmod(app.config["UP_RESOLVE"] + g.user.uuid + '/', "rw")  # 授权
            url = file_url
            form.url.data.save(app.config["UP_RESOLVE"] + g.user.uuid + '/' + url)
        resolve = Resolve(
            name=data['name'],
            description=data['description'],
            url=url,
            user_id=g.user.id,
            demand_id=demand.id
        )
        db.session.add(resolve)
        db.session.commit()
        flash("发布resolve成功", "ok")
        return redirect(url_for('main.resolve_release', demand_id=demand.id))
    return render_template('main/resolve_release.html', form=form)


@main.route('/improve/detail/<int:id>', methods=['GET', 'POST'])
@person_login_reg
def improve_detail(id=None):
    improve = Improve.query.get_or_404(int(id))
    form = GradeForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            data = form.data
            improve.score = data['score']
            improve.qua_score = data['qua_score']
            improve.com_score = data['com_score']
            improve.cre_score = data['cre_score']
            improve.word_score = data['word_score']
            improve.review = data['review']

            db.session.commit()
            return redirect(url_for('main.improve_detail', id=improve.id, page=-1))
    me = g.user
    is_user = session.get('is_user')
    return render_template('main/improve_detail.html', me=me, improve=improve, is_user=is_user,
                           form=form)


# demo
@main.route('/improve/release/<int:demo_id>', methods=['GET', 'POST'])
@user_login_reg
def improve_release(demo_id=None):
    demo = Demo.query.get_or_404(int(demo_id))
    form = ImproveForm()
    if form.validate_on_submit():
        data = form.data
        url = ""
        if form.url.data:
            file_url = form.url.data.filename
            if not os.path.exists(app.config["UP_IMPROVE"] + g.user.uuid + '/'):  # 如果不存在，则创建文件
                os.makedirs(app.config["UP_IMPROVE"] + g.user.uuid + '/')
                # os.chmod(app.config["UP_RESOLVE"] + g.user.uuid + '/', "rw")  # 授权
            url = file_url
            form.url.data.save(app.config["UP_IMPROVE"] + g.user.uuid + '/' + url)
        improve = Improve(
            name=data['name'],
            description=data['description'],
            url=url,
            user_id=g.user.id,
            demo_id=demo.id
        )
        db.session.add(improve)
        db.session.commit()
        flash("发布resolve成功", "ok")
        return redirect(url_for('main.improve_release', demo_id=demo.id))
    return render_template('main/improve_release.html', form=form)


@main.route('/resolve/detail/<int:id>/', methods=['GET', 'POST'])
@person_login_reg
def resolve_detail(id=None):
    resolve = Resolve.query.get_or_404(int(id))
    form = GradeForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            data = form.data
            resolve.score = data['score']
            resolve.qua_score = data['qua_score']
            resolve.com_score = data['com_score']
            resolve.cre_score = data['cre_score']
            resolve.word_score = data['word_score']
            resolve.review = data['review']

            db.session.commit()
            return redirect(url_for('main.resolve_detail', id=resolve.id, page=-1))
    me = g.user
    is_user = session.get('is_user')
    return render_template('main/resolve_detail.html', me=me, resolve=resolve, is_user=is_user,
                           form=form)


# demo
@main.route('/demo/release/', methods=['GET', 'POST'])
@user_login_reg
def demo_release():
    q = Tag.query
    tags = q.all()
    count = q.count()

    form = DemoForm()

    if form.validate_on_submit():
        data = form.data
        url = ""
        if form.url.data:
            file_url = form.url.data.filename
            if not os.path.exists(app.config["UP_DEMO"] + g.user.uuid + '/'):  # 如果不存在，则创建文件
                os.makedirs(app.config["UP_DEMO"] + g.user.uuid + '/')
                # os.chmod(app.config["UP_DEMO"] + g.user.uuid + '/', "rw")  # 授权
            url = file_url
            form.url.data.save(app.config["UP_DEMO"] + g.user.uuid + '/' + url)
        demo = Demo(
            name=data['name'],
            description=data['description'],
            per_price=data['per_price'],
            price=data['price'],
            url=url,
            user_id=g.user.id,
        )
        select = request.form.get("logo")
        demo.picture = select
        # 将文本提取关键词 转换成字典存储
        # txt = remove_tag(data['description'])
        # keywordlist = jieba.analyse.extract_tags(txt, topK=10, withWeight=True, allowPOS=('nz', 'n'))
        # dic = change_list_to_dic(keywordlist)
        # with open(app.static_folder + '/keyword/' + 'demokey.dat') as file:
        #     d = pickle.load(file)
        #     d[demo.id] = dic
        #     pickle.dump(d, file)
        #
        for tag_id in range(count):
            if request.form.get(str(tag_id)):
                tag = q.filter_by(id=tag_id).first()
                demo.tags.append(tag)

        db.session.add(demo)
        db.session.commit()
        flash("发布demo成功", "ok")
        return redirect(url_for('main.demo_release'))
    return render_template('main/demo_release.html', form=form, tags=tags)


# demo细节页面
@main.route('/demo/detail/<int:id>', methods=['GET', 'POST'])
@person_login_reg
def demo_detail(id=None):
    demo = Demo.query.get_or_404(int(id))
    form = CommentForm()
    picture = str(demo.picture)
    if request.method == 'POST':
        if form.validate_on_submit():
            data = form.data
            is_user = session.get('is_user')
            if is_user:

app/templates/main/demand_search.html
{% extends 'base/base.html' %}

{% import "ui/main_page.html" as pg %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='main/css/demand_list.css') }}">
{% endblock %}

{% block content %}

    <div style="background-color: rgb(231,231,231);">
        <!--  标     志 -->
        <div class="mylogo">
            <img src="{{ url_for('static', filename='main/img/logo_03.gif') }}" alt=""
                 style="margin-left: 20px;margin-top: 10px;float: left;">
            <h3>AIGO</h3>
            <h3 style="color: black;margin-left: 50px;font-size: 50px;">需求搜索</h3>
        </div>

        <!-- 主 题 展 示 -->
        <section>
            <div class="demo-show-main">
                <div class="labelbox">
                    <h4 class="checkbox-h4"></h4>
                </div>
                <div class="sort">
                    <h4 style="line-height: 8px;font-size: 18px;margin-left: 15px;">排序</h4>
                    <button id='b1' class="btn my-btn-nor" onclick="change(this)">智能排序</button>
                    <button id='b2' class="btn my-btn-nor" onclick="change(this)">demo来自</button>
                    <button id='b3' class="btn my-btn-nor" onclick="change(this)">发布时间<span
                            class="glyphicon glyphicon-arrow-up"></span></button>
                    <button id='b4' class="btn my-btn-nor" onclick="change(this)">star数<span
                            class="glyphicon glyphicon-arrow-up"></span></button>

                    {# <button type="submit" class="btn my-btn-search">筛选</button> #}
                </div>
                <div>
                    {% for v in page_data.items %}
                        <div class="demo-show">
                            <div class="number">
                                <a class="be-block" href="{{ url_for("main.demand_detail", id=v.id) }}">{{ v.name }}</a>
                                <br>
                                <h5>编号 {{ v.id }}</h5>
                            </div>
                            <div class="time">
                                <h5 style="margin-top: 10px;">发布者 {{ v.enterprise.name }}</h5>
                                <h5>demo来自 用户</h5>
                                <h5>发布时间 {{ v.addtime }}</h5>
                            </div>
                            <div class="collection">
                                <button style="background-color: white;border: none;color: black;"
                                        onclick="clickchange(this)"><span class="glyphicon glyphicon-star-empty"
                                                                          style="font-size: 30px;"></span></button>
                                <h5>{{ v.star }}</h5>
                            </div>
                            <div class="label-show">
                                标签
                                {% for tag in v.tags %}
                                    <span class="label label-primary">{{ tag.name }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="demo-show" style="border-bottom: none">
                        {{ pg.page(page_data, 'main.demand_list') }}
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='main/js/demand_list.js') }}" type="text/javascript" charset="utf-8"
            async defer></script>
{% endblock %}

app/templates/main/demo_list.html
{% extends 'base/base.html' %}

{% import "ui/main_page.html" as pg %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='main/css/demand_list.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='jquery-pretty-radio-checkbox/css/jquery-labelauty.css') }}">
    <style>
        ul {
            list-style-type: none;
        }

        li {
            display: inline-block;
        }

        input.labelauty + label {
            font: 16px "Microsoft Yahei";
        }
    </style>
{% endblock %}

{% block content %}

    {#    {% for data in page_data %}#}
    {#        <div>#}
    {#            <a href="{{ url_for('main.demo_detail', id=data.id) }}">{{ data.name }}</a>#}
    {#            {% for tag in data.tags %}#}
    {#                <p>{{ tag }}</p>#}
    {#            {% endfor %}#}
    {#        </div>#}
    {#    {% endfor %}#}

    <div style="background-color: rgb(231,231,231);">
        <!--  标     志 -->
        <div class="mylogo">
            <img src="{{ url_for('static', filename='main/img/logo_03.gif') }}" alt=""
                 style="margin-left: 20px;margin-top: 10px;float: left;">
            <h3>AIGO</h3>
            <h3 style="color: black;margin-left: 50px;font-size: 50px;">demo库</h3>
        </div>

        <!-- 主 题 展 示 -->
        <section>
            <div class="demo-show-main">
                <div class="labelbox">
                    <h4 class="checkbox-h4">技术标签</h4>
                </div>
                <form action="{{ url_for('main.demo_filter', page=1) }}" method="post">
                    <div class="checkbox-div">
                        <ul class="dowebok">

                            {% for tag in tags %}
                                <li><input type="checkbox" name="{{ tag.id }}"
                                           data-labelauty={{ tag.name }}></li>
                            {% endfor %}

                        </ul>
                        {#<button type="submit" class="btn my-btn-search">筛选</button>#}
                    </div>
                    <div class="select">
                        <button type="submit" class="btn my-btn-search">筛选</button>
                    </div>
                </form>
                <div class="sort">
                    <h4 style="line-height: 8px;font-size: 18px;margin-left: 15px;">排序</h4>
                   <a id='b1' class="btn my-btn-nor" onclick="change(this)" href="{{ url_for('main.demo_list', page=1) }}">智能排序</a>
                    <a id='b2' class="btn my-btn-nor" onclick="change(this)" href="{{ url_for('main.demo_list', page=1) }}?dn=1&time=0&star=0">名称排序</a>
                    <a id='b3' class="btn my-btn-nor" onclick="change(this)" href="{{ url_for('main.demo_list', page=1) }}?dn=0&time=1&star=0">发布时间<span
                            class="glyphicon glyphicon-arrow-up"></span></a>
                    <a id='b4' class="btn my-btn-nor" onclick="change(this)" href="{{ url_for('main.demo_list', page=1) }}?dn=0&time=0&star=1">star数<span
                            class="glyphicon glyphicon-arrow-up"></span></a>
                    {# <button type="submit" class="btn my-btn-search">筛选</button>#}
                </div>

                <div>
                    {% for v in page_data.items %}
                        <div class="demo-show">
                            <div class="number">
                                <a class="be-block" href="{{ url_for("main.demo_detail", id=v.id) }}">{{ v.name }}</a>
                                <br>
                                <h5>编号 {{ v.id }}</h5>
                            </div>
                            <div class="time">
                                <h5 style="margin-top: 10px;">发布者 {{ v.user.name }}</h5>
                                <h5>demo来自 用户</h5>
                                <h5>发布时间 {{ v.addtime }}</h5>
                            </div>
                            <div class="collection">
                                <button style="background-color: white;border: none;color: black;"
                                        onclick="clickchange(this)"><span class="glyphicon glyphicon-star-empty"
                                                                          style="font-size: 30px;"></span></button>
                                <h5>{{ v.star }}</h5>
                            </div>
                            <div class="label-show">
                                标签
                                {% for tag in v.tags %}
                                    <span class="label label-primary">{{ tag.name }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="demo-show" style="border-bottom: none">
                        {{ pg.page(page_data, 'main.demo_list') }}
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='main/js/demand_list.js') }}" type="text/javascript" charset="utf-8"
            async defer></script>
    <script src="{{ url_for('static', filename='jquery-pretty-radio-checkbox/js/jquery-labelauty.js') }}"></script>
    <script>
        $(function () {
            $(':input').labelauty();
        });
    </script>

{% endblock %}

app/templates/main/mail.html
{% extends 'base/base.html' %}

{% import "ui/main_page.html" as pg %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='main/css/demand_list.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='jquery-pretty-radio-checkbox/css/jquery-labelauty.css') }}">
    <style>
        ul {
            list-style-type: none;
        }

        li {
            display: inline-block;
        }

        input.labelauty + label {
            font: 16px "Microsoft Yahei";
        }
    </style>
{% endblock %}

{% block content %}

    {#    {% for data in page_data %}#}
    {#        <div>#}
    {#            <a href="{{ url_for('main.demo_detail', id=data.id) }}">{{ data.name }}</a>#}
    {#            {% for tag in data.tags %}#}
    {#                <p>{{ tag }}</p>#}
    {#            {% endfor %}#}
    {#        </div>#}
    {#    {% endfor %}#}

    <div style="background-color: rgb(231,231,231);">
        <!--  标     志 -->
        <div class="mylogo">
            <img src="{{ url_for('static', filename='main/img/logo_03.gif') }}" alt=""
                 style="margin-left: 20px;margin-top: 10px;float: left;">
            <h3>AIGO</h3>
            <h3 style="color: black;margin-left: 50px;font-size: 50px;">交易市场</h3>
        </div>

        <!-- 主 题 展 示 -->
        <section>
            <div class="demo-show-main">
                <div class="labelbox">
                    <h4 class="checkbox-h4">技术标签</h4>
                </div>
                <form action="{{ url_for('main.demo_filter', page=1) }}" method="post">
                    <div class="checkbox-div">
                        <ul class="dowebok">

                            {% for tag in tags %}
                                <li><input type="checkbox" name="{{ tag.id }}"
                                           data-labelauty={{ tag.name }}></li>
                            {% endfor %}

                        </ul>
                        {#<button type="submit" class="btn my-btn-search">筛选</button>#}
                    </div>
                    <div class="container select">
             <div class="dropdown" >
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                数据集
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="#">数据集</a></li>
                <li><a href="#">数据模型</a></li>

              </ul>
            </div>
              <div style="margin-left:700px; margin-top:-30px;">
             <button type="submit" class="btn my-btn-search" >筛选</button>
             </div></div>
                </form>
                <div class="sort">
                    <h4 style="line-height: 8px;font-size: 18px;margin-left: 15px;">排序</h4>
                   <a id='b1' class="btn my-btn-nor" onclick="change(this)" href="{{ url_for('main.demo_list', page=1) }}">智能排序</a>
                    <a id='b2' class="btn my-btn-nor" onclick="change(this)" href="{{ url_for('main.demo_list', page=1) }}?dn=1&time=0&star=0">名称排序</a>
                    <a id='b3' class="btn my-btn-nor" onclick="change(this)" href="{{ url_for('main.demo_list', page=1) }}?dn=0&time=1&star=0">发布时间<span
                            class="glyphicon glyphicon-arrow-up"></span></a>
                    <a id='b4' class="btn my-btn-nor" onclick="change(this)" href="{{ url_for('main.demo_list', page=1) }}?dn=0&time=0&star=1">star数<span
                            class="glyphicon glyphicon-arrow-up"></span></a>
                    {# <button type="submit" class="btn my-btn-search">筛选</button>#}
                </div>

                <div>
                    {% for v in page_data.items %}
                        <div class="demo-show">
                            <div class="number">
                                <a class="be-block" href="{{ url_for("main.demo_detail", id=v.id) }}">{{ v.name }}训练数据集</a>
                                <br>
                                <h5>编号 {{ v.id }}</h5>
                            </div>
                            <div class="time">
                                <h5 style="margin-top: 10px;">发布者 {{ v.user.name }}</h5>
                                <h5>商品来自 用户</h5>
                                <h5>发布时间 {{ v.addtime }}</h5>
                            </div>
                            <div class="collection">
                                <button style="background-color: white;border: none;color: black;"
                                        onclick="clickchange(this)"><span class="glyphicon glyphicon-star-empty"
                                                                          style="font-size: 30px;"></span></button>
                                <h5>{{ v.col_number(v) }}</h5>
                            </div>
                            <div class="label-show">
                                标签
                                {% for tag in v.tags %}
                                    <span>{{ tag.name }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="demo-show" style="border-bottom: none">
                        {{ pg.page(page_data, 'main.demo_list') }}
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='main/js/demand_list.js') }}" type="text/javascript" charset="utf-8"
            async defer></script>
    <script src="{{ url_for('static', filename='jquery-pretty-radio-checkbox/js/jquery-labelauty.js') }}"></script>
    <script>
        $(function () {
            $(':input').labelauty();
        });
    </script>

{% endblock %}

app/templates/main/result.html
{% for aspect in aspects %}
    <span class="badge default" style="font-size:20px;margin-left:5px;">&nbsp;aspect&nbsp;</span>
{% endfor %}

app/templates/main/user_list.html
{% extends 'base/base.html' %}

{% import "ui/main_page.html" as pg %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='main/css/user_list.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='jquery-pretty-radio-checkbox/css/jquery-labelauty.css') }}">
    <style>
        ul {
            list-style-type: none;
        }

        li {
            display: inline-block;
        }

        input.labelauty + label {
            font: 16px "Microsoft Yahei";
        }
    </style>
{% endblock %}

{% block content %}

    {#    {% for data in page_data %}#}
    {#        <div>#}
    {#            <a href="{{ url_for('main.demo_detail', id=data.id) }}">{{ data.name }}</a>#}
    {#            {% for tag in data.tags %}#}
    {#                <p>{{ tag }}</p>#}
    {#            {% endfor %}#}
    {#        </div>#}
    {#    {% endfor %}#}

    <div style="background-color: rgb(231,231,231);">
        <!--  标     志 -->
        <div class="mylogo">
            <img src="{{ url_for('static', filename='main/img/logo_03.gif') }}" alt=""
                 style="margin-left: 20px;margin-top: 10px;float: left;">
            <h3>AIGO</h3>
            <h3 style="color: black;margin-left: 50px;font-size: 50px;">人才库</h3>
        </div>

        <!-- 主 题 展 示 -->
        <section>
            <div class="demo-show-main">
                <div class="labelbox">
                    <h4 class="checkbox-h4">技术标签</h4>
                </div>
                <form action="{{ url_for('main.user_filter', page=1) }}" method="post">
                    <div class="checkbox-div">
                        <ul class="dowebok">

                            {% for tag in tags %}
                                <li><input type="checkbox" name="{{ tag.id }}"
                                           data-labelauty={{ tag.name }}></li>
                            {% endfor %}

                        </ul>
                        {#<button type="submit" class="btn my-btn-search">筛选</button>#}
                    </div>
                    <div class="select">
                        <button type="submit" class="btn my-btn-search">筛选</button>
                    </div>
                </form>

                <hr>

                <span>根据指定的指标进行人才的筛选</span>
                <form action="#">
                     <div style="margin-left: 25px;display: inline;">

                        <div style="display: inline">
                            {{ form.select }}
                        </div>
                        <span style="display: inline;">{{ form.submit }}</span>
                    </div>
                </form>
                <hr>
                <div class="sort">
                    <h4 style="line-height: 8px;font-size: 18px;margin-left: 15px;">排序</h4>
                    <a id='b1' class="btn my-btn-nor" onclick="change(this)"
                       href="{{ url_for('main.user_list', page=1) }}">智能排序</a>
                    <a id='b2' class="btn my-btn-nor" onclick="change(this)"
                       href="{{ url_for('main.user_list', page=1) }}?dn=1&time=0&star=0">名称排序</a>
                    <a id='b3' class="btn my-btn-nor" onclick="change(this)"
                       href="{{ url_for('main.user_list', page=1) }}?dn=0&time=1&star=0">注册时间<span
                            class="glyphicon glyphicon-arrow-up"></span></a>
                    <a id='b4' class="btn my-btn-nor" onclick="change(this)"
                       href="{{ url_for('main.user_list', page=1) }}?dn=0&time=0&star=1">粉丝数<span
                            class="glyphicon glyphicon-arrow-up"></span></a>
                    {# <button type="submit" class="btn my-btn-search">筛选</button>#}
                </div>

                <div>
                    <div class="human-div">
                        {% for v in page_data.items %}
                            <!--  下面的div是每个人才的条目 -->
                            <div class="demo-show" style="margin-top: 5px;">
                                {% if v.face %}
                                    <img src="{{ url_for('static', filename='uploads/user/'+v.uuid+'/'+v.face) }}"
                                         class="photo">
                                {% else %}
                                    <img src="holder.js/70x70" class="photo">
                                {% endif %}
                                <!--   下面的a链接是人才的名字链接到他的个人空间对外版 -->
                                <a href="{{ url_for("user.zone", user_id=v.id) }}">{{ v.name }}</a>
                                <h5>{{ v.addtime }}</h5>
                                <h5 style="margin-left: 5px;">注册</h5>
                                <table>
                                    <tr>
                                        <td class="numb" style="margin-left: 40px;">{{ v.demo_number(v) }}</td>
                                        <td class="numb">{{ v.fans }}</td>
                                    </tr>
                                    <tr>
                                        <td style="margin-left: 40px;">demo发布数</td>
                                        <td>粉丝数</td>
                                    </tr>
                                </table>
                            </div>
                        {% endfor %}
                        <div class="container" style="width:500px;">
                            <div id="pager" class="mypager" style="text-align: center;">
                                <div class="pagination">
                                    {{ pg.page(page_data, 'main.user_list') }}
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

        </section>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='main/js/demand_list.js') }}" type="text/javascript" charset="utf-8"
            async defer></script>
    <script src="{{ url_for('static', filename='jquery-pretty-radio-checkbox/js/jquery-labelauty.js') }}"></script>
    <script>
        $(function () {
            $(':input').labelauty();
        });
    </script>

{% endblock %}