app/enterprise/forms.py
# -*- coding:utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField, SelectField, BooleanField
from wtforms.validators import DataRequired, ValidationError, EqualTo, Email, Regexp
from app.models import Enterprise


class LoginForm(FlaskForm):
    """企业登录表单"""
    email = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号")
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱",
            "id": "input_contact",
            # "required": "required"
        },
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码"),
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码",
            "id": "input_pwd",
            # "required": "required"
        }
    )

    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-lg btn-info",
            "style": "margin-left: 20px;",
        }
    )

    def validate_email(self, field):
        email = field.data
        user = Enterprise.query.filter_by(email=email).count()
        if user == 0:
            raise ValidationError('账号不存在')


class RegisterForm(FlaskForm):
    """企业注册表单"""
    name = StringField(
        label="企业名称",
        validators=[
            DataRequired("请输入企业名称")
        ],
        description="企业名称",
        render_kw={
            "id": "input_name",
            "class": "form-control input-lg",
            "placeholder": "请输入企业名称",
        },
    )

    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "id": "input_email",
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱",

        },
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码"),
        ],
        description="密码",
        render_kw={
            "id": "input_password",
            "class": "form-control input-lg",
            "placeholder": "请输入密码",
        }
    )

    repwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请输入确认密码"),
            EqualTo('pwd', message="两次密码不相等")
        ],
        description="确认密码",
        render_kw={
            "id": "input_repassword",
            "class": "form-control input-lg",
            "placeholder": "请输入确认密码",
        }
    )

    submit = SubmitField(
        '注册',
        render_kw={
            "class": "btn btn-lg btn-success btn-block",
        }
    )


    def validate_name(self, field):
        name = field.data
        user = Enterprise.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError("企业名称已经存在")

    def validate_email(self, field):
        email = field.data
        user = Enterprise.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在")


class EnterpriseDetailForm(FlaskForm):
    """企业信息表单"""
    name = StringField(
        label="企业名称",
        validators=[
            DataRequired("请输入企业名称")
        ],
        description="企业名称",
        render_kw={
            "id": "input_name",
            "class": "form-control input-lg",
            "placeholder": "请输入企业名称",
        },
    )

    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱",
            "id": "input_contact",
            # "required": "required"
        },
    )

    phone = StringField(
        label="手机",
        # validators=[
        #     DataRequired("请输入手机"),
        #     Regexp("1[3458]\\d{9}", message='手机格式不正确！')
        # ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机",
            "id": "input_contact",
            # "required": "required"
        },
    )

    face = FileField(
        label="头像",
        # validators=[
        #     DataRequired("请上传头像")
        # ],
        description="头像"
    )

    qq = StringField(
        label="qq",
        validators=[
            DataRequired("请输入qq"),
        ],
        description="qq",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入qq",
            "id": "input_contact",
            # "required": "required"
        },
    )

    info = TextAreaField(
        label="简介",
        # validators=[
        #     DataRequired("请输入简介")
        # ],
        description="简介",
        render_kw={
            "class": "form-control",
            "row": 10,
        }
    )

    submit = SubmitField(
        ' 保存修改',
        render_kw={
            "class": "btn btn-success",
        }
    )

    def validate_email(self, field):
        email = field.data
        user = Enterprise.query.filter_by(email=email).count()
        if user == 0:
            raise ValidationError('账号不存在')


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label='旧密码',
        validators=[
            DataRequired("请输入旧密码"),
        ],
        description="旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入旧密码",
        }
    )

    new_pwd = PasswordField(
        label='新密码',
        validators=[
            DataRequired("请输入新密码"),
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码",
        }
    )

    submit = SubmitField(
        ' 修改密码',
        render_kw={
            "class": "btn btn-success",
        }
    )

app/enterprise/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

enterprise = Blueprint("enterprise", __name__)

from . import views

app/enterprise/views.py
# -*- coding:utf-8 -*-

from flask import render_template, redirect, url_for, flash, session, request, make_response, g
from app.enterprise.forms import LoginForm, RegisterForm, EnterpriseDetailForm, PwdForm
from app.models import Tag, Demo, Enterprise, Demand, Usercol, User
from . import enterprise
from werkzeug.security import generate_password_hash
from app import db, app
from app.decorators import enterprise_login_reg
import uuid, os, datetime, pickle


def change_filename(filename):
    fname, fext = os.path.splitext(filename)
    filename_prefix = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    return '%s%s%s' % (filename_prefix, str(uuid.uuid4().hex), fext)


# 企业主页
@enterprise.route('/', methods=['GET', 'POST'])
@enterprise_login_reg
def index():
    form = EnterpriseDetailForm()
    user = g.user

    form.face.validators = []
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data

        if form.face.data:
            file_face = form.face.data.filename
            if not os.path.exists(app.config["EF_DIR"] + g.user.uuid + '/'):
                os.makedirs(app.config["EF_DIR"] + g.user.uuid + '/')
                # os.chmod(app.config["EF_DIR"] + g.user.uuid + '/', "rw")
            user.face = change_filename(file_face)
            form.face.data.save(app.config["EF_DIR"] + g.user.uuid + '/' + user.face)

        name_count = Enterprise.query.filter_by(name=data['name']).count
        if data['name'] != user.name and name_count == 1:
            flash("昵称已经存在了", 'err')
            return redirect('user.index')
        email_count = Enterprise.query.filter_by(email=data['email']).count

        if data['email'] != user.email and email_count == 1:
            flash("邮箱已经存在了", 'err')
            return redirect('user.index')
        phone_count = Enterprise.query.filter_by(phone=data['phone']).count

        if data['phone'] != user.phone and phone_count == 1:
            flash("手机号码已经存在了", 'err')
            return redirect('enterprise.index')

        user.name = data['name']
        user.email = data['email']
        user.phone = data['phone']
        user.info = data['info']

        db.session.add(user)
        db.session.commit()
        flash('修改成功!', 'ok')
        return redirect(url_for('enterprise.index'))
    return render_template('enterprise/enterprise.html', form=form, user=user)


# 收藏demo列表
@enterprise.route('/demo_col/', methods=['GET', 'POST'])
@enterprise_login_reg
def demo_col():
    return render_template('enterprise/demo_col.html')


# 解决方案列表
@enterprise.route('/resolve/', methods=['GET', 'POST'])
@enterprise_login_reg
def resolve():
    return render_template('enterprise/resolve.html')


# 关注列表
@enterprise.route('/followed/', methods=['GET', 'POST'])
@enterprise_login_reg
def followed():
    follows = Usercol.query.filter_by(enterprise_id=g.user.id).filter_by(object=False).all()
    return render_template('enterprise/followed.html', follows=follows)


# 参与众筹列表
@enterprise.route('/crowd_funding/', methods=['GET', 'POST'])
@enterprise_login_reg
def crowd_funding():
    return render_template('enterprise/crowd_funding.html')


# 修改密码
@enterprise.route('/pwd/', methods=['GET', 'POST'])
@enterprise_login_reg
def pwd():
    form = PwdForm()
    user = g.user
    if form.validate_on_submit():
        data = form.data
        if not user.check_pwd(data['old_pwd']):
            flash('密码错误', 'err')
            return redirect(url_for('enterprise.pwd'))
        user.pwd = generate_password_hash(data["new_pwd"])
        db.session.add(user)
        db.session.commit()
        flash('修改密码成功,请重新登录', 'ok')
        return redirect(url_for('enterprise.logout'))
    return render_template('enterprise/pwd.html', form=form)


# 匹配结果
@enterprise.route('/match/', methods=['GET', 'POST'])
@enterprise_login_reg
def match():
    user_id = session.get('user_id')
    with open(app.static_folder + '/keyword/' + 'redemandlist.dat', 'rb') as file:
        d = pickle.load(file)

    redic = {}
    demanddic = {}
    for demand in Demand.query.filter_by(enterprise_id=user_id):
        reid = d[demand.id]
        demanddic[demand.id] = demand
        relist = []

        for id, score in reid:
            demo = Demo.query.filter_by(
                id=id
            ).first()
            relist.append(demo)
        redic[demand.id] = relist

    return render_template('enterprise/match.html', demanddic=demanddic, redic=redic)


# 用户画像
@enterprise.route('/portrait/', methods=['GET', 'POST'])
def portrait():
    user = g.user
    my_tags = user.tags.all()

    q = Tag.query
    tags = q.all()
    count = q.count()

    for tag in my_tags:
        tags.remove(tag)

    if request.method == 'POST':
        for tag in my_tags:
            user.tags.remove(tag)

        for tag_id in range(count):
            if request.form.get(str(tag_id)):
                tag = q.filter_by(id=tag_id).first()
                user.tags.append(tag)

        db.session.add(user)
        db.session.commit()

        my_tags = user.tags.all()

        q = Tag.query
        tags = q.all()
        count = q.count()

        for tag in my_tags:
            tags.remove(tag)

    return render_template('enterprise/portrait.html', tags=tags, my_tags=my_tags)


# 个人展示空间
@enterprise.route('/zone/<int:enterprise_id>', methods=['GET', 'POST'])
def zone(enterprise_id=None):
    enterprise = Enterprise.query.filter_by(id=enterprise_id).first()
    user_id = session.get('user_id')
    is_user = session.get('is_user')
    g.is_user = is_user
    if user_id and is_user:
        user1 = User.query.filter(User.id == user_id).first()
        if user1:
            me = user1
    elif user_id and not is_user:
        user1 = Enterprise.query.filter(Enterprise.id == user_id).first()
        if user1:
            me = user1
    if request.method == 'POST':
        if request.get_json()['mydata'] == 'follow':
            me.ent_follow(enterprise)
            return redirect(url_for('enterprise.zone', enterprise_id=enterprise.id))
        # 取消关注
        elif request.get_json()['mydata'] == 'unfollow':
            me.ent_unfollow(enterprise)
            return redirect(url_for('enterprise.zone', enterprise_id=enterprise.id))
    return render_template('enterprise/Zone.html', user=enterprise, me=me, is_user=is_user)


# 注册
@enterprise.route('/register/', methods=['GET', 'POST'])
def register():
    q = Tag.query
    tags = q.all()
    count = q.count()

    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = Enterprise(
            name=data['name'],
            email=data['email'],
            pwd=generate_password_hash(data['pwd']),
            uuid=uuid.uuid4().hex
        )
        for tag_id in range(count):
            if request.form.get(str(tag_id)):
                tag = q.filter_by(id=tag_id).first()
                user.tags.append(tag)

        db.session.add(user)
        db.session.commit()
        flash("注册成功", "ok")

    return render_template('enterprise/register.html', form=form, tags=tags)


# 登录
@enterprise.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    nexturl = request.args.get('next')

    if form.validate_on_submit():
        data = form.data
        user = Enterprise.query.filter_by(email=data['email']).first()
        if not user.check_pwd(data['pwd']):
            flash('密码错误', 'err')
            return redirect(url_for('enterprise.login'))
        session["is_user"] = False
        session["user_id"] = user.id

        return redirect(nexturl or url_for('enterprise.index'))
    return render_template('enterprise/login.html', form=form)


# 登出
@enterprise.route('/logout/')
@enterprise_login_reg
def logout():
    session.clear()
    return redirect(url_for("enterprise.login"))


@enterprise.before_request
def my_before_request():
    user_id = session.get('user_id')
    if user_id:
        user = Enterprise.query.filter(Enterprise.id == user_id).first()
        if user:
            g.user = user


@enterprise.context_processor
def my_context_processpr():
    if hasattr(g, 'user'):
        return {'user': g.user, 'is_user': False}
    return {}

app/templates/enterprise/Zone.html
{% extends 'base/base.html' %}
{% block content %}

<div class="main-body">
<div id="container">
    <div class="rect" id="panel-top">
        <div id="container-img-background"><img src="{{ url_for('static', filename='user/images/背景_1.gif') }}" alt="" id="img-background"></div>
        <p id="label-my-title">{{user.name}}的个人空间</p>
        <p id="label-my-describe">{{user.info}}</p>
        <div class="lable" id="container-label-my3">
            <p id="label-my-follows">关注：{{user.follow_ent(user)}}</p>
            <p id="label-my-fans">粉丝：{{user.ent_follow(user)}}</p>

        </div>
        {%if is_user%}
        {%if not me.is_following(user)%}
        <button type="button" class="btn-blue-line" id="btn-follow" name="follow"><span>关注</span></button>
        {%else%}
        <button type="button" class="btn-blue-line" id="btn-follow" name="unfollow"><span>取消关注</span></button>
        {%endif%}
        {%endif%}

        <button type="button" class="btn-blue-line" id="btn-message">私信</button>
    </div>
    <div id="panel-left">
        <div class="rect" id="userinfo">
            {% if user.face %}
            <img src="{{ url_for('static', filename='uploads/enterprise/'+user.uuid+'/'+user.face) }}" class="rect"
                 alt="头像" id="img-head">
            {% else %}
                <img src="holder.js/144x144" class="img-responsive img-rounded" id="img-head">
            {% endif %}

            <div id="container-label-user5">
                <p class="label-userinfo" id="label-user-nick">公司名称：{{user.name}}</p>

            </div>
        </div>
        <div class="rect" id="crowdfunding">
            <div id="contianer-label-crowdfunding">
                <div class="blue-rect" id="blue-rect-small4"></div>
                <p id="label-crowdfunding">众筹经历</p>
            </div>
            <p class="label-userinfo" id="label-crowdfunding1">TA参与的：{{user.cf_count(user)}}</p>
            <button type="button" class="btn-blue-line" id="btn-view">查看</button>
        </div>
    </div>
    <div id="panel-mid">
        <div class="rect" id="portrait">
            <div id="contianer-label-user-protrait">
                <div class="blue-rect" id="blue-rect1"></div>
                <p id="label-user-protrait">企业画像</p>
            </div>
            <div id="container-graph-protrait">
                <div class="rect" id="graph-protrait1">
                    <div id="contianer-label-user-protrait1">
                        <div class="blue-rect" id="blue-rect-small1"></div>
                        <p id="label-user-protrait1">综合能力评价</p>
                    </div>
                </div>
                <div class="rect" id="graph-protrait2">
                    <div id="contianer-label-user-protrait2">
                        <div class="blue-rect" id="blue-rect-small2"></div>
                        <p id="label-user-protrait2">个人评价</p>
                    </div>
                </div>
                <div class="rect" id="graph-protrait3">
                    <div id="contianer-label-user-protrait3">
                        <div class="blue-rect" id="blue-rect-small3"></div>
                        <p id="label-user-protrait3">他人评价</p>
                    </div>
                </div>
            </div>
        </div>
         <div class="rect" id="demo">
            <div class="container" id="contianer-label-demo">
                <div class="blue-rect" id="blue-rect2"></div>
                <p id="label-demo">TA发布的需求</p>
            </div>
            <div class="container" id="contianer-label-demos">
                {%for data in user.demands%}
                <p class="label-demo" id="label-demo1"><a class="title" href="{{url_for('main.demand_detail', id=data.id, page=-1)}}">{{data.name}}&nbsp;&nbsp;&nbsp;&nbsp;{{data.addtime}}</a></p>
                {%endfor%}
            </div>
        </div>

    </div>
</div>
    </div>
</body>
</html>
{% endblock %}

{% block js %}


<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user/css/Zone.css') }}"/>

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>

<script>
             $(document).ready(function () {
            $("#btn-follow").click(function () {

                if (this.name == "follow" ) {
                    var data = {
                        'mydata': 'follow'
                    };
                    this.innerHTML = "<span>取消关注</span>";
                    this.name="unfollow";
                    location.reload();
                    $.ajax(
                        {
                            type: 'POST',
                            contentType: 'application/json; charset=UTF-8',
                            url: "{{ url_for('enterprise.zone', enterprise_id=user.id) }}",
                            data: JSON.stringify(data),
                            success: function (data) {
                            }
                        });
                }
                else if (this.name == "unfollow" ) {
                    var data = {
                        'mydata': 'unfollow'
                    };
                    this.innerHTML = "<span>关注</span>";
                    this.name="unfollow";
                    location.reload();
                    $.ajax(
                        {
                            type: 'POST',
                            contentType: 'application/json; charset=UTF-8',
                            url: "{{ url_for('enterprise.zone', enterprise_id=user.id) }}",
                            data: JSON.stringify(data),
                            success: function (data) {

                            }
                        });
                }

            });
        });

</script>
{% endblock %}

app/templates/enterprise/menu.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Ai-go</title>

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/base.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user/css/person-homepage.css') }}"/>
    {% block css %}{% endblock %}
</head>
<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!--导航-->
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{{ url_for('main.index') }}">首页
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('main.demand_release') }}">发布需求</a>
                </li>
                <li>
                    <a href="{{ url_for('main.demo_release') }}">发布demo</a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;" method="post"
                  action="{{ url_for('main.search', page=1) }}">
                <div class="form-group input-group">
                    <div class="input-group-btn">
                        <button id="option" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">demo <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="#" id="option-1">demo</a></li>
                            <li><a href="#" id="option-2">需求</a></li>
                            <li><a href="#" id="option-3">人才</a></li>
                        </ul>
                        <input type="text" name="methods" id="methods" hidden value="1">
                    </div>
                    <input type="text" name="key" class="form-control" placeholder="请输关键词！" id="key_moive">
                    <span class="input-group-btn">
                        <button class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</button>
                    </span>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                {% if user %}
                    <li>
                        <a class="curlink"
                           href="{% if is_user==True %}{{ url_for('user.logout') }}{% elif is_user==False %}{{ url_for('enterprise.logout') }}{% endif %}">
                            <span class="glyphicon glyphicon-log-out"></span>&nbsp;注销</a>
                    </li>
                {% else %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('user.login') }}">个人登录</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for('enterprise.login') }}">企业登录</a></li>
                        </ul>
                    </li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('user.register') }}">个人注册</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ url_for('enterprise.register') }}">企业注册</a></li>
                    </ul>
                </li>
                <li>
                    <a class="curlink" href="{% if is_user == True %}{{ url_for('user.index') }}{% elif is_user == False %}{{ url_for('enterprise.index') }}{% else %}{{ url_for('user.login') }}{% endif %}">
                        <span class="glyphicon glyphicon-user"></span>&nbsp;个人中心</a>
                </li>
                <li>
                    <a class="curlink" href="../user/user.html">
                        <span class="glyphicon glyphicon-envelope"></span>&nbsp;私信</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container-fluid" style="padding-right: 0px; padding-left: 0px; margin-top: 74px">
    <section>
        <div class="main-body">
            <div class="my-top" style="position: relative;">
                {% if user.face %}
                    <img src="{{ url_for('static', filename='uploads/enterprise/'+user.uuid+'/'+user.face) }}" alt=""
                        class="photo">
                {% else %}
                    <img src="holder.js/100x100" class="img-responsive img-rounded photo">
                {% endif %}
                <a href="{{ url_for('user.index') }}"><span class="change">修改资料</span></a>
                <!-- p最多写4行 -->
                <h4>
                    {{ user.name }}
                    <p> {{ user.info }}
                    </p>
                </h4>
            </div>
            <div>
                <div class="myleft">
                    <ul>
                        <li>
                            <a id="m-1" href="{{ url_for('enterprise.match') }}">
                                &nbsp;我的需求
                            </a>
                        </li>
                        <li>
                            <a id="m-2" href="{{ url_for('enterprise.resolve') }}">
                                &nbsp;解决方案
                            </a>
                        </li>
                        <li>
                            <a id="m-4" href="{{ url_for('enterprise.pwd') }}">
                                &nbsp;修改密码
                            </a>
                        </li>
                        <li>
                            <a id="m-5" href="{{ url_for('enterprise.demo_col') }}">
                                &nbsp;收藏项目
                            </a>
                        </li>
                        <li>
                            <a id="m-6" href="{{ url_for('enterprise.followed') }}">
                                &nbsp;关注列表
                            </a>
                        </li>
                        <!--
                        <li>
                            <a id="m-7" href="{{ url_for('enterprise.crowd_funding') }}">&nbsp;众筹demo</a>
                        </li>
                        -->
                        <li>
                            <a id="m-8" href="{{ url_for('enterprise.portrait') }}">
                                &nbsp;我的画像
                            </a>
                        </li>
                    </ul>
                </div>

                {% block builtin %}{% endblock %}

            </div>
        </div>
    </section>
</div>
<!--内容-->
<!--底部-->
<footer class="myfooter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    版本©&nbsp;2017-2018 归 青青草原 所有&nbsp;版本 1.0
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        $("img").lazyload({
            effect: "fadeIn",
            threshold: 40
        });
        var caret = '<span class="caret"></span>';
        $("#option-1").click(function () {
            $("#option").html("demo " + caret);
            $("#methods").attr("value", 1)
        });
        $("#option-2").click(function () {
            $("#option").html("需求 " + caret);
            $("#methods").attr("value", 2)
        });
        $("#option-3").click(function () {
            $("#option").html("人才 " + caret);
            $("#methods").attr("value", 1)
        });
    });
</script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/enterprise/portrait.html
{% extends 'enterprise/menu.html' %}

{% block css %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='jquery-pretty-radio-checkbox/css/jquery-labelauty.css') }}">
    <style>
        dowebok. ul {
            list-style-type: none;
        }

        .dowebok li {
            display: inline-block;
        }

        .dowebok li {
            margin: 10px 0;
        }
    </style>
{% endblock %}

{% block builtin %}
    <div class="row" >

        <div class="col-md-6">

                <div class="panel-body">
                    <form role="form" method="post" action="{{ url_for('enterprise.portrait') }}">
                        <div class="form-group">
                            <label for=""><span
                                    class="glyphicon glyphicon-music"></span> 我感兴趣的标签</label>

                            <ul class="dowebok">
                                {% for tag in tags %}
                                    <li><input type="checkbox" name="{{ tag.id }}"
                                               data-labelauty={{ tag.name }}></li>
                                {% endfor %}
                                {% for tag in my_tags %}
                                    <li><input type="checkbox" name="{{ tag.id }}"
                                               data-labelauty={{ tag.name }} checked></li>
                                {% endfor %}
                            </ul>
                            <button type="submit" class="btn btn-info">修改</button>
                        </div>
                    </form>

                </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript"
            src="{{ url_for('static', filename='datepicker/bootstrap-datetimepicker.min.js') }}" charset="UTF-8"></script>
    <script type="text/javascript">
        CKEDITOR.replace('description', {
            {#        开启上传功能，配置上传路径#}
            filebrowserUploadUrl: '/demandupload/'
        });
    </script>
    <script src="{{ url_for('static', filename='jquery-pretty-radio-checkbox/js/jquery-labelauty.js') }}"></script>
    <script>
        $(function () {
            $(':input').labelauty();
        });
    </script>
{% endblock %}