app/user/forms.py
# -*- coding:utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired, ValidationError, EqualTo, Email, Regexp
from app.models import User
from app.ext.evaluate import *


class RegisterForm(FlaskForm):
    """会员注册表单"""
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称")
        ],
        description="昵称",
        render_kw={
            "id": "input_name",
            "class": "form-control input-lg",
            "placeholder": "请输入昵称",
        },
    )

    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "id": "input_email",
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱",

        },
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码"),
        ],
        description="密码",
        render_kw={
            "id": "input_password",
            "class": "form-control input-lg",
            "placeholder": "请输入密码",
        }
    )

    repwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请输入确认密码"),
            EqualTo('pwd', message="两次密码不相等")
        ],
        description="确认密码",
        render_kw={
            "id": "input_repassword",
            "class": "form-control input-lg",
            "placeholder": "请输入确认密码",
        }
    )

    submit = SubmitField(
        '注册',
        render_kw={
            "class": "btn btn-lg btn-success btn-block",
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError("昵称已经存在")

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在")


class LoginForm(FlaskForm):
    """会员登录表单"""
    email = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号")
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱",
            "id": "input_contact",
            # "required": "required"
        },
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码"),
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码",
            "id": "input_pwd",
            # "required": "required"
        }
    )

    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-lg btn-info ",
            "style": "margin-left: 20px;",
        }
    )

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 0:
            raise ValidationError('账号不存在')


class UserDetailForm(FlaskForm):
    """会员信息表单"""
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称")
        ],
        description="昵称",
        render_kw={
            "id": "input_name",
            "class": "form-control input-lg",
            "placeholder": "请输入昵称",
        },
    )

    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱",
            "id": "input_contact",
            # "required": "required"
        },
    )

    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机"),
            Regexp("1[3458]\\d{9}", message='手机格式不正确！')
        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机",
            "id": "input_contact",
            # "required": "required"
        },
    )

    face = FileField(
        label="头像",
        # validators=[
        #     DataRequired("请上传头像")
        # ],
        description="头像"
    )

    qq = StringField(
        label="qq",
        validators=[
            DataRequired("请输入qq"),
        ],
        description="qq",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入qq",
            "id": "input_contact",
            # "required": "required"
        },
    )

    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("请输入简介")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "row": 10,
        }
    )

    recommand = SelectField(
        label="配置推荐方式",
        coerce=int,
        description="推荐方式",
        choices=[(1, "根据兴趣推荐"), (2, "根据历史行为推荐"), (3, "不要给我推荐")],
        render_kw={
            "class": "form-control"
        }
    )

    submit = SubmitField(
        ' 保存修改',
        render_kw={
            "class": "btn btn-success",
        }
    )


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label='旧密码',
        validators=[
            DataRequired("请输入旧密码"),
        ],
        description="旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入旧密码",
        }
    )

    new_pwd = PasswordField(
        label='新密码',
        validators=[
            DataRequired("请输入新密码"),
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码",
        }
    )

    submit = SubmitField(
        ' 修改密码',
        render_kw={
            "class": "btn btn-success",
        }
    )


class PortraitForm(FlaskForm):
    choice = []
    i = 0
    for e in EVALUATE:
        choice.append((i, e))
        i = i + 1

    select = SelectMultipleField(
        '请选择要查看的指标',
        choices=choice,
        render_kw={
            "class": "form-group",
        }
    )

    submit = SubmitField(
        '筛选',
        render_kw={
            "class": "btn btn-info",
        }
    )

app/user/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

user = Blueprint("user", __name__)

from . import views

app/user/views.py
# -*- coding:utf-8 -*-

from flask import render_template, redirect, url_for, flash, session, request, g
from app.user.forms import LoginForm, RegisterForm, UserDetailForm, PwdForm, PortraitForm
from app.models import Tag, Demo, User, Demand, Enterprise, Usercol
from . import user
from werkzeug.security import generate_password_hash
from app import db, app
from app.decorators import user_login_reg, person_login_reg
import uuid, os, datetime, pickle
from app.ext.evaluate import *
from app.ext.generator import generate_graph


def change_filename(filename):
    fname, fext = os.path.splitext(filename)
    filename_prefix = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    return '%s%s%s' % (filename_prefix, str(uuid.uuid4().hex), fext)


# 生成一个知识图谱 输入为图谱名称id
def generate_graph(id):
    import csv
    # 读取csv文件
    with open(app.static_folder + '/keyword/' + str(id) + '.csv') as f:
        reader = csv.reader(f)
        lis = list(reader)[1:]
        nodes = [{"name": l[1]} for l in lis]
    with open(app.static_folder + '/keyword/' + str(id) + 'r.csv') as f:
        reader = csv.reader(f)
        lisref = list(reader)[1:]
        edges = [{"source": int(e[0]) - 1, "target": int(e[1]) - 1} for e in lisref]
    return nodes, edges


# 用户主页
@user.route('/', methods=['GET', 'POST'])
@user_login_reg
def index():
    form = UserDetailForm()
    user = g.user
    form.face.validators = []
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data

        if form.face.data:
            file_face = form.face.data.filename
            if not os.path.exists(app.config["UF_DIR"] + g.user.uuid + '/'):
                os.makedirs(app.config["UF_DIR"] + g.user.uuid + '/')
                # os.chmod(app.config["UF_DIR"] + g.user.uuid + '/', "rw")
            user.face = change_filename(file_face)
            form.face.data.save(app.config["UF_DIR"] + g.user.uuid + '/' + user.face)

        name_count = User.query.filter_by(name=data['name']).count
        if data['name'] != user.name and name_count == 1:
            flash("昵称已经存在了", 'err')
            return redirect('user.index')
        email_count = User.query.filter_by(email=data['email']).count

        if data['email'] != user.email and email_count == 1:
            flash("邮箱已经存在了", 'err')
            return redirect('user.index')
        phone_count = User.query.filter_by(phone=data['phone']).count

        if data['phone'] != user.phone and phone_count == 1:
            flash("手机号码已经存在了", 'err')
            return redirect('user.index')

        user.name = data['name']
        user.email = data['email']
        user.phone = data['phone']
        user.info = data['info']
        user.recommand_method = data['recommand']

        db.session.add(user)
        db.session.commit()
        flash('修改成功!', 'ok')
        return redirect(url_for('user.index'))
    return render_template('user/user.html', form=form)


# 修改密码
@user.route('/pwd/', methods=['GET', 'POST'])
@user_login_reg
def pwd():
    form = PwdForm()
    user = g.user
    if form.validate_on_submit():
        data = form.data
        if not user.check_pwd(data['old_pwd']):
            flash('密码错误', 'err')
            return redirect(url_for('user.pwd'))
        user.pwd = generate_password_hash(data["new_pwd"])
        db.session.add(user)
        db.session.commit()
        flash('修改密码成功,请重新登录', 'ok')
        return redirect(url_for('user.logout'))
    return render_template('user/pwd.html', form=form)


# 个人展示空间
@user.route('/zone/<int:user_id>', methods=['GET', 'POST'])
@person_login_reg
def zone(user_id=None):
    form = PortraitForm()
    # 用户画像部分
    from pyecharts import Radar
    score1 = []
    score2 = []
    score3 = []
    for cal in CAL_EVALUATE:
        score1.append(cal(user=None))
        score2.append(cal(user=None))
        score3.append(cal(user=None))

    c_schema = [{"name": e, "max": 100} for e in EVALUATE]  # 构建评价指标

    value_bj = [score1]
    radar1 = Radar(width=280, height=300)
    radar1.config(c_schema=c_schema)
    radar1.add("人才画像", value_bj, item_color="#f9713c", is_area_show=True, area_color="#f9713c", area_opacity=0.5)

    value_bj = [score2]
    radar2 = Radar(width=280, height=300)
    radar2.config(c_schema=c_schema)
    radar2.add("人才画像", value_bj, item_color="#f9713c", is_area_show=True, area_color="#f9713c", area_opacity=0.5)

    value_bj = [score3]
    radar3 = Radar(width=280, height=300)
    radar3.config(c_schema=c_schema)
    radar3.add("人才画像", value_bj, item_color="#f9713c", is_area_show=True, area_color="#f9713c", area_opacity=0.5)

    # 后端处理部分
    user = User.query.filter_by(id=user_id).first()
    user_id = session.get('user_id')
    is_user = session.get('is_user')
    g.is_user = is_user
    if user_id and is_user:
        user1 = User.query.filter(User.id == user_id).first()
        if user1:
            me = user1
    elif user_id and not is_user:
        user1 = Enterprise.query.filter(Enterprise.id == user_id).first()
        if user1:
            me = user1
    if request.method == 'POST':
        if request.get_json()['mydata'] == 'follow':
            me.follow(user)
            return redirect(url_for('user.zone', user_id=user.id))
        # 取消关注
        elif request.get_json()['mydata'] == 'unfollow':
            me.unfollow(user)
            return redirect(url_for('user.zone', user_id=user.id))
    return render_template('user/Zone.html', user=user, me=me,
                           myechart1=radar1.render_embed(), myechart2=radar2.render_embed(),
                           myechart3=radar3.render_embed(), form=form)


# 匹配结果
@user.route('/match/', methods=['GET', 'POST'])
@user_login_reg
def match():
    user_id = session.get('user_id')
    with open(app.static_folder + '/keyword/' + 'redemolist.dat', 'rb') as file:
        d = pickle.load(file)

    redic = {}
    demodic = {}

    for demo in Demo.query.filter_by(user_id=user_id):
        reid = d[demo.id]
        demodic[demo.id] = demo
        relist = []

        for id, score in reid:
            demand = Demand.query.filter_by(
                id=id
            ).first()
            relist.append(demand)
        redic[demo.id] = relist

    return render_template('user/match.html', demodic=demodic, redic=redic)


# 用户画像
@user.route('/portrait/', methods=['GET', 'POST'])
@user_login_reg
def portrait():
    form = PortraitForm()
    from pyecharts import Radar

    if request.method == 'GET':
        score = []
        for cal in CAL_EVALUATE:
            score.append(cal(user=g.user))
        value_bj = [score]
        c_schema = [{"name": e, "max": 100} for e in EVALUATE]
        radar = Radar(width=500, height=350)
        radar.config(c_schema=c_schema)
        radar.add("人才画像", value_bj, item_color="#f9713c", is_area_show=True, area_color="#f9713c", area_opacity=0.5)

        score = []
        for cal in CAL_EVALUATE:
            score.append(cal(user=g.user)+random.randint(2, 8))
        value_bj = [score]
        c_schema = [{"name": e, "max": 100} for e in EVALUATE]
        radar1 = Radar(width=500, height=350)
        radar1.config(c_schema=c_schema)
        radar1.add("人才画像", value_bj, item_color="#f9713c", is_area_show=True, area_color="#f9713c", area_opacity=0.5)
        # radar.render_embed()

    if request.method == 'POST':
        select = list(map(int, form.data['select']))    # 高阶函数 转换为int
        print(select)

        score = []
        c_schema = []
        for num in select:
            score.append(CAL_EVALUATE[num](user=g.user))
            c_schema.append({"name": EVALUATE[num], "max": 100})
        value_bj = [score]

        radar = Radar(width=500, height=350)
        radar.config(c_schema=c_schema)
        radar.add("人才画像", value_bj, item_color="#f9713c", is_area_show=True, area_color="#f9713c", area_opacity=0.5)

        score = []
        for cal in CAL_EVALUATE:
            score.append(cal(user=g.user) + random.randint(2, 8))
        value_bj = [score]
        c_schema = [{"name": e, "max": 100} for e in EVALUATE]
        radar1 = Radar(width=500, height=350)
        radar1.config(c_schema=c_schema)
        radar1.add("人才画像", value_bj, item_color="#f9713c", is_area_show=True, area_color="#f9713c", area_opacity=0.5)
        # radar.render_embed()

    # 更改用户的兴趣
    user = g.user
    my_tags = user.tags.all()

    q = Tag.query
    tags = q.all()
    count = q.count()

    # for tag in my_tags:
    #     tags.remove(tag)
    flag = False
    for i in range(count):
        if request.form.get(str(i)) is not None:
            flag = True
            break

    if request.method == 'POST' and flag:
        for tag in my_tags:
            user.tags.remove(tag)

        for tag_id in range(count):
            if request.form.get(str(tag_id)):
                tag = q.filter_by(id=tag_id).first()
                user.tags.append(tag)

        db.session.add(user)
        db.session.commit()

        my_tags = user.tags.all()

        q = Tag.query
        tags = q.all()
        count = q.count()

    return render_template('user/portrait.html', form=form,
                           tags=tags, my_tags=my_tags, myechart=radar.render_embed(), myechart1=radar1.render_embed())


# 知识图谱
@user.route('/knowledge_graph/', methods=['GET', 'POST'])
@user_login_reg
def knowledge_graph():
    if request.method == 'GET':
        nodes, edges = generate_graph('ai')
    else:
        nodes, edges = generate_graph('nlp')

    return render_template('user/knowledge_graph.html', nodes=nodes, edges=edges)


# 游戏化机制
@user.route('/gamification/', methods=['GET', 'POST'])
@user_login_reg
def gamification():
    return render_template('user/gamification.html')


# 登录
@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    nexturl = request.args.get('next')

app/templates/user/crowd_funding.html
{% extends 'user/menu.html' %}

{% block builtin %}
    <div class="container">
        <div class="col-md-9">
            <div class="myright">
                <div class="R-top">
                    <p>
                        <b>我参与的众筹</b>
                    </p>
                </div>

                <div class="R-bottom">
                    {% for data in user.democfs %}
                        <div class="mylike">
                            <h3>
                                <a href="">{{ data.find_demo(data).name }}</a>
                            </h3>
                            <a href="" class="like-comp">

                                <img src="{{ url_for('static',
                                filename='uploads/user/'+data.find_demo(data).user.uuid+'/'+data.find_demo(data).user.face) }}"
                                     class="img-responsive img-rounded" width="100px">
                            </a>
                            <h4>&nbsp;&nbsp;&nbsp;demo作者：{{ data.find_demo(data).user.name }}</h4>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
{% endblock %}

app/templates/user/login.html
{% extends "base/base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='main/css/login.css') }}">
{% endblock %}

{% block content %}
    <!--内容-->
    <div class="row"
         style="background-image: url({{ url_for('static', filename='main/img/登录_02.gif') }}); background-size: 100%; height: 100%;">
        <div class="col-md-4 col-md-offset-1">
            <br><br>
            <p class="idea-p">问渠那得清如许
                <br><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;为有源头活水来
                <br><br><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AIGO,助你思如泉涌
            </p>
        </div>
        <div class="col-md-3 col-md-offset-2" style="margin-top: 100px; margin-bottom: 70px">
            <div class="panel panel-primary">
                {#<div class="panel-heading">#}
                {#<h3 class="panel-title"><span class="glyphicon glyphicon-log-in"></span>&nbsp;用户登录</h3>#}
                {#</div>#}
                <div class="my-header">
                    <img src="{{ url_for('static', filename='main/img/logo_03.gif') }}" alt=""
                         style="margin-left: 70px;margin-top: 10px;">
                    <h4 class="my-h4">AIGO</h4>
                </div>
                <!-- 企业或者用户 -->
                <div class="center-block" style="margin-left: 70px; margin-top: 10px;">
                    <a class="btn btn-info" href="{{ url_for('user.login') }}" style="display: inline-block" role="button">个人登录</a>
                    <a class="btn btn-default" href="{{ url_for('enterprise.login') }}" style="display: inline-block" role="button">企业登录</a>
                </div>
                <div class="panel-body">
                    {% for msg in get_flashed_messages(category_filter=["err"]) %}
                        <p class="login-box-msg" style="color: red">{{ msg }}</p>
                    {% endfor %}
                    {% for msg in get_flashed_messages(category_filter=["ok"]) %}
                        <p class="login-box-msg" style="color: green">{{ msg }}</p>
                    {% endfor %}
                    <form role="form" method="post">
                        <fieldset>
                            <div class="form-group">
                                <label for="input_contact"><span
                                        class="glyphicon glyphicon-user"></span> {{ form.email.label }}</label>
                                {{ form.email }}
                            </div>
                            {% for err in form.email.errors %}
                                <div class="col-md-12" id="error_contact">
                                    <font style="color: red">{{ err }}</font>
                                </div>
                            {% endfor %}

                            <div class="form-group">
                                <label for="input_password"><span
                                        class="glyphicon glyphicon-lock"></span> {{ form.pwd.label }}</label>
                                {{ form.pwd }}
                            </div>
                            {% for err in form.pwd.errors %}
                                <div class="col-md-12" id="input_user">
                                    <font style="color: red">{{ err }}</font>
                                </div>
                            {% endfor %}

                            <div>
                                {{ form.csrf_token }}
                                {{ form.submit }}
                                <a href="#" class="my-a">忘记密码?</a>
                                <a href="{{ url_for('user.register') }}" class="my-a">新用户</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/user/menu.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Ai-go</title>

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/base.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user/css/person-homepage.css') }}"/>
    {% block css %}{% endblock %}
</head>
<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!--导航-->
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{{ url_for('main.index') }}">首页
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('main.demand_release') }}">发布需求</a>
                </li>
                <li>
                    <a href="{{ url_for('main.demo_release') }}">发布demo</a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;" method="post"
                  action="{{ url_for('main.search', page=1) }}">
                <div class="form-group input-group">
                    <div class="input-group-btn">
                        <button id="option" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">demo <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="#" id="option-1">demo</a></li>
                            <li><a href="#" id="option-2">需求</a></li>
                            <li><a href="#" id="option-3">人才</a></li>
                        </ul>
                        <input type="text" name="methods" id="methods" hidden value="1">
                    </div>
                    <input type="text" name="key" class="form-control" placeholder="请输关键词！" id="key_moive">
                    <span class="input-group-btn">
                        <button class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</button>
                    </span>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                {% if user %}
                    <li>
                        <a class="curlink"
                           href="{% if is_user==True %}{{ url_for('user.logout') }}{% elif is_user==False %}{{ url_for('enterprise.logout') }}{% endif %}">
                            <span class="glyphicon glyphicon-log-out"></span>&nbsp;注销</a>
                    </li>
                {% else %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('user.login') }}">个人登录</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for('enterprise.login') }}">企业登录</a></li>
                        </ul>
                    </li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('user.register') }}">个人注册</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ url_for('enterprise.register') }}">企业注册</a></li>
                    </ul>
                </li>
                <li>
                    <a class="curlink" href="{% if is_user == True %}{{ url_for('user.index') }}{% elif is_user == False %}{{ url_for('enterprise.index') }}{% else %}{{ url_for('user.login') }}{% endif %}">
                        <span class="glyphicon glyphicon-user"></span>&nbsp;个人中心</a>
                </li>
                <li>
                    <a class="curlink" href="../user/user.html">
                        <span class="glyphicon glyphicon-envelope"></span>&nbsp;私信</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container-fluid" style="padding-right: 0px; padding-left: 0px; margin-top: 74px">
    <section>
        <div class="main-body">
            <div class="my-top" style="position: relative;">
                {% if user.face %}
                    <img src="{{ url_for('static', filename='uploads/user/'+user.uuid+'/'+user.face) }}" alt=""
                         class="photo">
                {% else %}
                    <img src="holder.js/100x100" class="img-responsive img-rounded photo">
                {% endif %}
                <a href="{{ url_for('user.index') }}"><span class="change">修改资料</span></a>
                <!-- p最多写4行 -->
                <h4>
                    {{ user.name }}
                    <p> {{ user.info }}
                    </p>
                </h4>
            </div>
            <div>
                <div class="myleft">
                    <ul>
                        <li>
                            <a id="m-1" href="{{ url_for('user.match') }}">
                                &nbsp;我的demo
                            </a>
                        </li>
                        <li>
                            <a id="m-2" href="{{ url_for('user.resolve') }}">
                                &nbsp;我的方案
                            </a>
                        </li>
                        <li>
                            <a id="m-4" href="{{ url_for('user.pwd') }}">
                                &nbsp;修改密码
                            </a>
                        </li>
                        <li>
                            <a id="m-5" href="{{ url_for('user.demo_col') }}">
                                &nbsp;收藏项目
                            </a>
                        </li>
                        <li>
                            <a id="m-6" href="{{ url_for('user.followed') }}">
                                &nbsp;我的关注
                            </a>
                        </li>
                        <!--
                        <li>
                            <a id="m-8" href="{{ url_for('user.crowd_funding') }}">&nbsp;众筹demo</a>
                        </li>
                        -->
                        <li>
                            <a id="m-9" href="{{ url_for('user.portrait') }}">
                                &nbsp;我的画像
                            </a>
                        </li>
                        <li>
                            <a id="m-10" href="{{ url_for('user.knowledge_graph') }}">
                                &nbsp;知识图谱
                            </a>
                        </li>
                        <li>
                            <a id="m-11" href="{{ url_for('user.gamification') }}">
                                &nbsp;学习进程
                            </a>
                        </li>

                        <li>
                            <a id="m-12" href="{{ url_for('user.my_improve') }}">
                                &nbsp;我的改进
                            </a>
                        </li>

                    </ul>
                </div>

                {% block builtin %}{% endblock %}

            </div>
        </div>
    </section>
</div>
<!--内容-->
<!--底部-->
<footer class="myfooter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    版本©&nbsp;2017-2018 归 青青草原 所有&nbsp;版本 1.0
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        $("img").lazyload({
            effect: "fadeIn",
            threshold: 40
        });
        var caret = '<span class="caret"></span>';
        $("#option-1").click(function () {
            $("#option").html("demo " + caret);
            $("#methods").attr("value", 1)
        });
        $("#option-2").click(function () {
            $("#option").html("需求 " + caret);
            $("#methods").attr("value", 2)
        });
        $("#option-3").click(function () {
            $("#option").html("人才 " + caret);
            $("#methods").attr("value", 1)
        });
    });
</script>
{% block js %}{% endblock %}
</body>
</html>