app/bbs/forms.py
# -*- coding:utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FileField, TextAreaField, SelectField
from wtforms.validators import DataRequired

from app.models import Plate
from app.ext import flaskckeditor


class CKEditorForm(FlaskForm):
    title = StringField(
        label="帖子名称",
        validators=[
            DataRequired("请输入帖子名称")
        ],
        description="帖子名称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入帖子名称",
            "id": "input_contact",
            # "required": "required"
        },
    )
    ckdemo = TextAreaField()
    belongedPlate = SelectField('所属版块:', coerce=int)
    url = FileField(
        label="附件",
        validators=[
            DataRequired("请上传附件")
        ],
        description="附件"
    )
    submit = SubmitField('submit')

    def __init__(self, *args, **kwargs):
        super(CKEditorForm, self).__init__(*args, **kwargs)
        self.belongedPlate.choices = [(belongedPlate.id, belongedPlate.title)
                                      for belongedPlate in Plate.query.all()]


class CommentForm(FlaskForm):
    ckdemo = TextAreaField()

    submit = SubmitField('submit')

app/bbs/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

bbs = Blueprint("bbs", __name__)

from . import views

app/bbs/views.py
# -*- coding:utf-8 -*-

import datetime
import os
import uuid
from datetime import datetime

from flask import render_template, redirect, url_for, flash, session, request, make_response, g

from app import db, app
from app.bbs.forms import CKEditorForm, CommentForm
from app.decorators import user_login_reg
from app.models import Tag, Enterprise, Article, Review, User, Plate, Collect, Praise, Moderator, Discuss
from . import bbs


# 生成文件名
def gen_rnd_filename():
    filename_prefix = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    return '%s%s' % (filename_prefix, str(uuid.uuid4().hex))


# 论坛主页路由
@bbs.route('/', methods=['GET', 'POST'])
def index():
    # 分别过滤出四个版块最多评论的六篇文章
    articles1 = Article.query.filter_by(plate_id=1).order_by(Article.reviews_number.desc()).limit(6)
    articles2 = Article.query.filter_by(plate_id=2).order_by(Article.reviews_number.desc()).limit(6)
    articles3 = Article.query.filter_by(plate_id=3).order_by(Article.reviews_number.desc()).limit(6)
    articles4 = Article.query.filter_by(plate_id=4).order_by(Article.reviews_number.desc()).limit(6)
    return render_template('bbs/bbs.html', articles1=articles1, articles2=articles2, articles3=articles3,
                           articles4=articles4)


# 发帖页面路由
@bbs.route('/post/', methods=['GET', 'POST'])
@user_login_reg
def post_message():
    q = Tag.query
    tags = q.all()
    count = q.count()

    form = CKEditorForm()
    if form.validate_on_submit():
        data = form.data
        file_url = form.url.data.filename
        if not os.path.exists(app.config["UP_ARTICLE"] + g.user.uuid + '/'):  # 如果不存在，则创建文件
            os.makedirs(app.config["UP_ARTICLE"] + g.user.uuid + '/')
        url = file_url
        form.url.data.save(app.config["UP_ARTICLE"] + g.user.uuid + '/' + url)
        article = Article(
            title=data['title'],
            description=data['ckdemo'],
            url=url,
            author_id=g.user.id,
            plate_id=data['belongedPlate']
        )

        for tag_id in range(count):
            if request.form.get(str(tag_id)):
                tag = q.filter_by(id=tag_id).first()
                article.tags.append(tag)
        db.session.add(article)
        db.session.commit()
        flash("发布article成功", "ok")
        return redirect(url_for('bbs.index'))
    return render_template('bbs/post.html', form=form, tags=tags)


# 帖子详情页面路由，其中版块id与文章id是变量
@bbs.route('/article/detail/<int:plate_id>/<int:id>', methods=['GET', 'POST'])
@user_login_reg
def article_detail(plate_id=None, id=None):
    plate = Plate.query.get_or_404(int(plate_id))
    # 判断用户是否是版主
    is_moderator = False
    if not Moderator.query.filter_by(plate_id=plate.id).filter_by(moderator_id=g.user.id) == None:
        is_moderator = True
    article = Article.query.get_or_404(int(id))
    form = CommentForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            data = form.data
            comment = Review(description=data['ckdemo'],
                             article_id=article.id,
                             author_id=g.user.id,
                             is_big=True)
            db.session.add(comment)
            article.reviews_number = article.reviews_number + 1
            article.last_review_time = datetime.today()
            db.session.commit()
            return redirect(url_for('bbs.article_detail', plate_id=plate.id, id=article.id, page=-1))
        # 点赞
        elif request.get_json()['mydata'] == 'add':
            userPraise = Praise.query.filter_by(giver_id=g.user.id).first()
            if userPraise == None:
                praise = Praise(article_id=article.id,
                                giver_id=g.user.id)
                db.session.add(praise)
                db.session.commit()
                return redirect(url_for('bbs.article_detail', plate_id=plate.id, id=article.id, page=-1))
        # 取消点赞
        elif request.get_json()['mydata'] == 'delete':
            userPraise = Praise.query.filter_by(giver_id=g.user.id).first()
            if not userPraise == None:
                db.session.delete(userPraise)
                db.session.commit()
                return redirect(url_for('bbs.article_detail', plate_id=plate.id, id=article.id, page=-1))
        # 收藏
        elif request.get_json()['mydata'] == 'favorite':
            userCollect = Collect.query.filter_by(giver_id=g.user.id).first()
            if userCollect == None:
                collect = Collect(article_id=article.id,
                                  giver_id=g.user.id)
                db.session.add(collect)
                db.session.commit()
                return redirect(url_for('bbs.article_detail', plate_id=plate.id, id=article.id, page=-1))
        # 取消收藏
        elif request.get_json()['mydata'] == 'unfavorite':
            userCollect = Collect.query.filter_by(giver_id=g.user.id).first()
            if not userCollect == None:
                db.session.delete(userCollect)
                db.session.commit()
                return redirect(url_for('bbs.article_detail', plate_id=plate.id, id=article.id, page=-1))
        # 删除评论，包括大评论和小评论
        elif request.get_json()['mydata'] == 'delete_review':
            delete_review = Review.query.filter_by(id=request.get_json()['review_id']).first()
            # 如果是大评论
            if delete_review.is_big == True:
                # 先找出大评论涉及到的关系
                delete_disscusses = Discuss.query.filter_by(discussed_id=delete_review.id).all()
                for discuss in delete_disscusses:
                    # 用关系找到小评论
                    small_reviews = Review.query.filter_by(id=discuss.discusser_id).first()
                    # 删删删
                    db.session.delete(small_reviews)
                    db.session.delete(discuss)
                    # 评论数减1
                    article.reviews_number = article.reviews_number - 1
            db.session.delete(delete_review)
            article.reviews_number = article.reviews_number - 1
            db.session.commit()
            return redirect(url_for('bbs.article_detail', plate_id=plate.id, id=article.id, page=-1))
        # 给大评论添加小评论
        elif request.get_json()['mydata'] == 'small_review':
            big_review = Review.query.filter_by(id=request.get_json()['review_id']).first()
            small_review = Review(description=request.get_json()['context'],
                                  article_id=article.id,
                                  author_id=g.user.id,
                                  )
            db.session.add(small_review)
            # 建立关系，用到models.py里的函数
            big_review.discuss(small_review)
            # 更新一下文章评论的情况
            article.reviews_number = article.reviews_number + 1
            article.last_review_time = datetime.today()
            db.session.commit()
            return redirect(url_for('bbs.article_detail', plate_id=plate.id, id=article.id, page=-1))
    # 找出所有大评论
    comment = Review.query.filter_by(article_id=article.id).filter_by(is_big=True).order_by(Review.addtime.desc())
    number = comment.count()
    # 获取收藏情况
    myCollect = Collect.query.filter_by(article_id=article.id)
    collectNumber = myCollect.count()
    # 获取点赞情况
    myPraise = Praise.query.filter_by(article_id=article.id)
    praiseNumber = myPraise.count()
    userPraise = Praise.query.filter_by(giver_id=g.user.id).first()
    userCollect = Collect.query.filter_by(collector_id=g.user.id).first()
    page = request.args.get('page', 1, type=int)
    pagination = comment.paginate(
        page, per_page=20,
        error_out=False)
    # 找出所有评论
    reviews = Review.query.filter_by(article_id=article.id).order_by(Review.addtime.desc())
    my_id = g.user.id
    return render_template('bbs/article_detail.html', article=article, plate=plate, is_moderator=is_moderator,
                           my_id=my_id,
                           form=form, reviews=reviews, pagination=pagination, userPraise=userPraise,
                           userCollect=userCollect,
                           number=number, collectNumber=collectNumber, praiseNumber=praiseNumber)


# 帖子列表的路由
@bbs.route('/article/list/<int:plate_id>', methods=['GET', 'POST'])
@user_login_reg
def article_list(plate_id=None):
    plate = Plate.query.get_or_404(int(plate_id))
    is_moderator = False
    if not Moderator.query.filter_by(plate_id=plate.id).filter_by(moderator_id=g.user.id) == None:
        is_moderator = True
    # 如果不是精华帖
    page = request.args.get('page', 1, type=int)
    pagination = Article.query.filter_by(plate_id=plate.id).order_by(Article.last_review_time.desc()).paginate(
        page, per_page=20, error_out=False)
    posts = pagination.items
    # 如果是精华帖的情况
    pagination_elite = Article.query.filter_by(plate_id=plate.id).filter_by(is_elite=True).order_by(
        Article.last_review_time.desc()).paginate(
        page, per_page=20, error_out=False)
    posts_elite = pagination_elite.items

    if request.method == 'POST':
        # 加精
        if request.get_json()['mydata'] == 'highlight':
            highlight_article = Article.query.filter_by(id=request.get_json()['article_id']).first()
            highlight_article.is_elite = True
            db.session.commit()
            return redirect(url_for('bbs.article_list', plate_id=plate.id))
        # 取消加精
        elif request.get_json()['mydata'] == 'unhighlight':
            highlight_article = Article.query.filter_by(id=request.get_json()['article_id']).first()
            highlight_article.is_elite = False
            db.session.commit()
            return redirect(url_for('bbs.article_list', plate_id=plate.id))
        # 删除文章
        elif request.get_json()['mydata'] == 'delete':
            delete_article = Article.query.filter_by(id=request.get_json()['article_id']).first()
            # 删除文章内所有回复
            delete_reviews = Review.query.filter_by(article_id=request.get_json()['article_id']).all()
            for review in delete_reviews:

app/templates/bbs/article_list.html
{% extends 'bbs/bbs_base.html' %}
{% import "bbs/paginate.html" as macros %}
{% import "bbs/article_list_table.html" as list_macros %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/forum.css') }}" charset="utf-8"/>
{% endblock %}
{% block content %}
    <section>
        <div class="mytop">
            <div class="logo-btn">
                <div class="logo">
                    <img src="{{ url_for('static', filename='bbs/images/logo.gif') }}" alt="">
                </div>
                <div class="row btn-area1">
                    <h1>
                        AIGO
                    </h1>
                    <a href="{{ url_for('bbs.index') }}">首页</a>
                    {% if plate.id == 1 %}
                        <a href="{{ url_for('bbs.article_list', plate_id=1) }}" class="myactive">人工智能</a>
                    {% else %}
                        <a href="{{ url_for('bbs.article_list', plate_id=1) }}">人工智能</a>
                    {% endif %}
                    {% if plate.id == 2 %}
                        <a href="{{ url_for('bbs.article_list', plate_id=2) }}" class="myactive">分享交流</a>
                    {% else %}
                        <a href="{{ url_for('bbs.article_list', plate_id=2) }}">分享交流</a>
                    {% endif %}
                    {% if plate.id == 3 %}
                        <a href="{{ url_for('bbs.article_list', plate_id=1) }}" class="myactive">活动专区</a>
                    {% else %}
                        <a href="{{ url_for('bbs.article_list', plate_id=1) }}">活动专区</a>
                    {% endif %}
                    {% if plate.id == 4 %}
                        <a href="{{ url_for('bbs.article_list', plate_id=1) }}" class="myactive">职场招聘</a>
                    {% else %}
                        <a href="{{ url_for('bbs.article_list', plate_id=1) }}">职场招聘</a>
                    {% endif %}
                </div>
            </div>
            <div class="row introduction">
                <img src="{{ url_for('static', filename='bbs/images/图片1_03.gif') }}" alt="" class="introduction-img" style="display: inline">
                <p style="display: inline; float: right">
                    版块介绍：图像识别，是指利用计算机对图像进行处理、分析和理解，以识别各种 不同模式的目标和对像的技术。一般工业使用中，采用工业相机拍摄图片，然后再 利用软件根据图片灰阶差做进一步识别处理。
                </p>
                <span class="hoster"> 版主：瑞瑞</span>
            </div>
        </div>
    </section>

    <section>
        <div class="mainbody">
            <!-- 上面那个标签分页栏 -->
            <div class="btn-area2" style="position: relative; height: 45px;">
                <button name="topic" id="btn1" class="btn mybtn"
                        style="background-color: white; margin-left: 100px; border-left:1.5px solid #CECECE ;border-right:1.5px solid #CECECE ">
                    主题
                </button>
                <button name="elite" id="btn2" class="btn mybtn" style="margin-left: 250px;">精华</button>
                <a href="{{ url_for('bbs.post_message') }}">发新帖</a>
            </div>
            <!-- 列出文章 -->
            <div id="list" style=" display:block; ">
                {{ list_macros.article_list_table(posts,plate=plate,is_moderator=is_moderator) }}
            </div>
            <div id="list_elite" style=" display:none; ">
                {{ list_macros.article_list_table(posts_elite,plate=plate,is_moderator=is_moderator) }}
            </div>
        </div>

        <!-- 下面把分页给居中 -->
        <div class="container">
            <div id="pager" class="mypager">
                <div id="page_norm" class="pagination">
                    {{ macros.pagination_widget(pagination, 'bbs.article_list',plate_id=plate.id) }}
                </div>
                <div id="page_elite" class="pagination" style=" display:none; ">
                    {{ macros.pagination_widget(pagination_elite, 'bbs.article_list',plate_id=plate.id) }}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

<!-- js代码，主要是ajax -->
{% block js %}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script>
        $(document).ready(function () {
            $(".highlight").click(function () {
                {% for data in posts %}
                    if (this.name == "highlight-{{ data.id }}") {
                        var data = {
                            'mydata': 'highlight',
                            'article_id':{{data.id}}
                        };
                        this.innerHTML = "<span>取消加精</span>";
                        this.name = "unhighlight-{{ data.id }}";
                        location.reload();
                        alert("加精成功");
                        $.ajax(
                            {
                                type: 'POST',
                                contentType: 'application/json; charset=UTF-8',
                                url: "{{ url_for('bbs.article_list', plate_id=plate.id) }}",
                                data: JSON.stringify(data),
                                success: function (data) {
                                }
                            });
                    }
                    else if (this.name == "unhighlight-{{ data.id }}") {
                        var data = {
                            'mydata': 'unhighlight',
                            'article_id':{{data.id}}
                        };
                        this.innerHTML = "<span>加为精华</span>";
                        document.getElementById("highlight-{{ data.id }}").innerHTML = "<span></span>";
                        this.name = "highlight-{{ data.id }}";
                        alert("取消加精成功");
                        location.reload();
                        $.ajax(
                            {
                                type: 'POST',
                                contentType: 'application/json; charset=UTF-8',
                                url: "{{ url_for('bbs.article_list', plate_id=plate.id) }}",
                                data: JSON.stringify(data),
                                success: function (data) {
                                }
                            });
                    }
                {% endfor %}
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $(".delete").click(function () {
                {% for data in posts %}
                    if (this.name == "delete-{{data.id }}") {
                        var data = {
                            'mydata': 'delete',
                            'article_id':{{data.id}}
                        };
                        document.getElementById("{{ data.id }}").innerHTML = "<span></span>";
                        $.ajax(
                            {
                                type: 'POST',
                                contentType: 'application/json; charset=UTF-8',
                                url: "{{ url_for('bbs.article_list', plate_id=plate.id) }}",
                                data: JSON.stringify(data),
                                success: function (data) {
                                }
                            });
                    }
                {% endfor %}
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $("#btn1").click(function () {
                $('#btn2').css({
                    background: '#EBE7E7',
                });
                $('#list').show();
                $('#list_elite').hide();
                $('#page_norm').show();
                $('#page_elite').hide();
                this.style.background = "white";
                this.style.borderLeft = "1.5px solid #CECECE";
                this.style.borderRight = "1.5px solid #CECECE";
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $("#btn2").click(function () {
                $('#btn1').css({
                    background: '#EBE7E7',
                });
                $('#list').hide();
                $('#list_elite').show();
                $('#page_norm').hide();
                $('#page_elite').show();
                this.style.background = "white";
                this.style.borderLeft = "1.5px solid #CECECE";
                this.style.borderRight = "1.5px solid #CECECE";
            });
        });
    </script>

{% endblock %}

app/templates/bbs/article_list_table.html
{% macro article_list_table(posts,plate,is_moderator) %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bbs/css/forum.css') }}" charset="utf-8"/>
    <!-- 如果不是版主，下面不用看，没调过 -->
    {% if is_moderator == false %}
        {% for data in posts %}
            <!-- 文章 -->
            <div class="article" style="margin-top: -2.5px;position: relative;">
                <a class="title"
                   href="{{ url_for('bbs.article_detail', plate_id=plate.id,id=data.id) }}">{{ data.title }}</a>
                <h4 class="author"> {{ data.author.name }}
                </h4>
                <text class="review">
                    {{ data.reviews_number }}评论 &nbsp&nbsp&nbsp&nbsp 最后回复时间{{ data.last_review_time }}
                </text>
            </div>
        {% endfor %}
        <!-- 如果是版主，下面开始看 -->
    {% else %}
        {% for data in posts %}
            <div class="container" id="{{ data.id }}">
                <!-- 文章标题和一些信息 -->
                <div class="article" style="margin-top: -2.5px;position: relative;">
                    <a class="title" href="{{ url_for('bbs.article_detail', plate_id=plate.id,id=data.id) }}">
                     <span id="highlight-{{ data.id }}">
                        <!-- 如果是精华文章，前面加一个红色的精华标签 -->
                         {% if data.is_elite == True %}
                             <span style="color:#f00">[精华]</span>
                         {% else %}
                             <span></span>
                         {% endif %}
                     </span>
                        {{ data.title }}
                    </a>
                    <h4 class="author">{{ data.author.name }}</h4>
                    <text class="review">
                        {{ data.reviews_number }}评论 &nbsp&nbsp&nbsp&nbsp 最后回复时间{{ data.last_review_time }}
                    </text>
                </div>
                <!-- 功能按钮 -->
                <div class="hoster-fun">
                    <!-- 加精按钮 -->
                    <div class="btn1">
                        {% if data.is_elite == True %}
                            <button class="highlight" name="unhighlight-{{ data.id }}">
                                <span>取消加精</span>
                            </button>
                        {% else %}
                            <button class="highlight" name="highlight-{{ data.id }}">
                                <span>加为精华</span>
                            </button>
                        {% endif %}
                    </div>
                    <!-- 删除按钮 -->
                    <div class="btn2">
                        <button class="delete" name="delete-{{ data.id }}">
                            <span>删除</span>
                        </button>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endmacro %}

app/templates/bbs/bbs.html
{% extends 'bbs/bbs_base.html' %}
{% block css %}

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bbs/css/forum.css') }}"
          charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bbs/css/home.css') }}" charset="utf-8"/>
{% endblock %}
{% block content %}
    <section>
        <div class="my-home-top">
            <div class="logo-btn">
                <div class="logo">
                    <img src="{{ url_for('static', filename='bbs/images/logo.gif') }}" alt="">
                </div>
                <div class="row btn-area1">
                    <h1>
                        AIGO
                    </h1>
                    <a href="{{ url_for('bbs.index') }}" class="myactive">首页</a>
                    <a href="{{ url_for('bbs.article_list', plate_id=1) }}">人工智能</a>
                    <a href="{{ url_for('bbs.article_list', plate_id=2) }}">分享交流</a>
                    <a href="{{ url_for('bbs.article_list', plate_id=1) }}">活动专区</a>
                    <a href="{{ url_for('bbs.article_list', plate_id=1) }}">职场招聘</a>
                </div>
            </div>

            <div class="row introduction">
                <div style="display: inline;">
                    <img src="{{ url_for('static', filename='bbs/images/图片1_03.gif') }}" alt=""
                         class="introduction-img">
                </div>
                <div style="display: inline; float: right">
                    <p>一周热点技术：图像识别，是指利用计算机对图像进行处理、分析和理解，以识别各种 不同模式的目标和对像的技术。一般工业使用中，采用工业相机拍摄图片，然后再 利用软件根据图片灰阶差做进一步识别处理。
                    </p>
                </div>

            </div>
            <div>&nbsp;</div>
        </div>
    </section>
    <!-- 下面开始每一块的主体 -->
    <section>
        <!-- 第一版块 -->
        <div class="mainbody" style="background-color: rgb(235,231,231);">
            <div class="home-part-show">
                <div>
                    <button class="home-btn">
                        人工智能
                    </button>
                </div>
                {% for data in articles1 %}
                    <div class="home-article">
                        <a href="{{ url_for('bbs.article_detail', plate_id=1,id=data.id) }}">{{ data.title }}</a>
                        <h4 class="home-author">
                            {{ data.author.name }}
                        </h4>
                        <h4 class="home-time">
                            最新回复{{ data.last_review_time }}
                        </h4>
                        <text>
                            {{ data.reviews_number }}评论
                        </text>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- 第二版块 -->
        <div class="mainbody" style="background-color: rgb(235,231,231);">
            <div class="home-part-show">
                <div>
                    <button class="home-btn">
                        分享交流
                    </button>
                </div>
                {% for data in articles2 %}
                    <div class="home-article">
                        <a href="{{ url_for('bbs.article_detail', plate_id=1,id=data.id) }}">{{ data.title }}</a>
                        <h4 class="home-author">
                            {{ data.author.name }}
                        </h4>
                        <h4 class="home-time">
                            最新回复{{ data.last_review_time }}
                        </h4>
                        <text>
                            {{ data.reviews_number }}评论
                        </text>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- 第三版块 -->
        <div class="mainbody" style="background-color: rgb(235,231,231);">
            <div class="home-part-show">
                <div>
                    <button class="home-btn">
                        活动专区
                    </button>
                </div>
                {% for data in articles1 %}
                    <div class="home-article">
                        <a href="{{ url_for('bbs.article_detail', plate_id=1,id=data.id) }}">{{ data.title }}</a>
                        <h4 class="home-author">
                            {{ data.author.name }}
                        </h4>
                        <h4 class="home-time">
                            最新回复{{ data.last_review_time }}
                        </h4>
                        <text>
                            {{ data.reviews_number }}评论
                        </text>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- 第四版块 -->
        <div class="mainbody" style="background-color: rgb(235,231,231);">
            <div class="home-part-show">
                <div>
                    <button class="home-btn">
                        职场招聘
                    </button>
                </div>
                {% for data in articles1 %}
                    <div class="home-article">
                        <a href="{{ url_for('bbs.article_detail', plate_id=1,id=data.id) }}">{{ data.title }}</a>
                        <h4 class="home-author">
                            {{ data.author.name }}
                        </h4>
                        <h4 class="home-time">
                            最新回复{{ data.last_review_time }}
                        </h4>
                        <text>
                            {{ data.reviews_number }}评论
                        </text>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

app/templates/bbs/paginate.html
<!-- 复制粘贴来用的分页代码 -->
<!DOCTYPE html>
<html lang="zh-CN">
{% macro pagination_widget(pagination, endpoint) %}
    <ul class="pagination">
        <li {% if not pagination.has_prev %} class="disabled"{% endif %}>
            <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">
                &laquo;
            </a>
        </li>
        {% for p in pagination.iter_pages() %}
            {% if p %}
                {% if p == pagination.page %}
                    <li class="active">
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="disabled"><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}
        <li {% if not pagination.has_next %} class="disabled"{% endif %}>
            <a href="{% if pagination.has_next %}{{ url_for(endpoint,
page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
                &raquo;
            </a>
        </li>
    </ul>
    </html>
{% endmacro %}

app/templates/bbs/post.html
{% extends 'bbs/bbs_base.html' %}
{% block content %}
    <head>
        <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
    </head>
    <body>
    <div class="container" style="padding:20px">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-plus"></span>&nbsp;发表帖子</h3>
            </div>
            <div class='panel-body'>
                <form method="post" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}

                    <div class="form-group">
                        {{ form.title(class='form-control', placeholder='请输入标题', type='text') }}
                    </div>
                    <div class="form-group">
                        {{ form.ckdemo(class='ckeditor') }}
                        <script type="text/javascript">
                            CKEDITOR.replace("ckdemo", {
                                filebrowserUploadUrl: 'bbs/ckupload/'
                            });
                        </script>
                    </div>
                    <div class="form-group">
                        {{ form.url(class='form-control', placeholder='请插入附件') }}
                    </div>
                    <div class="dropdown">

                        {{ form.belongedPlate(class="dropdown") }}

                    </div>
                    <div class="form-group box-footer ">
                        {{ form.submit(class="btn btn-success col-md-8 col-md-offset-2") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
    </body>

{% endblock %}